items:
  item1:
    name: "Gift to %name%"
    material: STONE
    custommodeldata: 2
    lore:
      - "Eid mobarak %name%"
    enchantments:
      durability: 3
    itemflags:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES

  skullitem:
    name: "Special %name% Head"
    material: PLAYER_HEAD
    skulltexture: "texture_url_here"

# Commands to execute when /eidi is run
# %player% will be replaced with the player's name
eidi_commands:
  - "tell %player% Happy Eid!"
  - "give %player% diamond 1"
eidi_messages:
  - "§aHappy Eid, %player%!"
  - "§6Enjoy your special gift!"
  - "§eA firework has been launched for you!"